package in.safety.domain;
// Generated Jul 29, 2017 6:39:12 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcademicCourses generated by hbm2java
 */
@Entity
@Table(name = "ACADEMIC_COURSES", catalog = "SafetyDB")
public class AcademicCourses implements java.io.Serializable {

	private Integer idAcademicCourses;
	private String courseName;
	private String courseCode;
	private Byte courseDurationMonths;
	private Set instituteCourseses = new HashSet(0);
	private Set jseekerMasters = new HashSet(0);

	public AcademicCourses() {
	}

	public AcademicCourses(String courseName, String courseCode, Byte courseDurationMonths, Set instituteCourseses,
			Set jseekerMasters) {
		this.courseName = courseName;
		this.courseCode = courseCode;
		this.courseDurationMonths = courseDurationMonths;
		this.instituteCourseses = instituteCourseses;
		this.jseekerMasters = jseekerMasters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ACADEMIC_COURSES", unique = true, nullable = false)
	public Integer getIdAcademicCourses() {
		return this.idAcademicCourses;
	}

	public void setIdAcademicCourses(Integer idAcademicCourses) {
		this.idAcademicCourses = idAcademicCourses;
	}

	@Column(name = "COURSE_NAME", length = 100)
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "COURSE_CODE", length = 5)
	public String getCourseCode() {
		return this.courseCode;
	}

	public void setCourseCode(String courseCode) {
		this.courseCode = courseCode;
	}

	@Column(name = "COURSE_DURATION_MONTHS")
	public Byte getCourseDurationMonths() {
		return this.courseDurationMonths;
	}

	public void setCourseDurationMonths(Byte courseDurationMonths) {
		this.courseDurationMonths = courseDurationMonths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "academicCourses")
	public Set getInstituteCourseses() {
		return this.instituteCourseses;
	}

	public void setInstituteCourseses(Set instituteCourseses) {
		this.instituteCourseses = instituteCourseses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "academicCourses")
	public Set getJseekerMasters() {
		return this.jseekerMasters;
	}

	public void setJseekerMasters(Set jseekerMasters) {
		this.jseekerMasters = jseekerMasters;
	}

}
