package in.safety.domain;
// Generated Jul 21, 2017 11:15:05 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmployerMaster generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYER_MASTER", catalog = "SafetyDB")
public class EmployerMaster implements java.io.Serializable {

	private Integer idEmployerMaster;
	private String employerName;
	private String employerAddr1;
	private String employerAddr2;
	private String employerCity;
	private String employerState;
	private String employerPincode;
	private String employerCountry;
	private String employerType;
	private Set jobPostings = new HashSet(0);

	public EmployerMaster() {
	}

	public EmployerMaster(String employerName, String employerAddr1, String employerAddr2, String employerCity,
			String employerState, String employerPincode, String employerCountry, String employerType,
			Set jobPostings) {
		this.employerName = employerName;
		this.employerAddr1 = employerAddr1;
		this.employerAddr2 = employerAddr2;
		this.employerCity = employerCity;
		this.employerState = employerState;
		this.employerPincode = employerPincode;
		this.employerCountry = employerCountry;
		this.employerType = employerType;
		this.jobPostings = jobPostings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_EMPLOYER_MASTER", unique = true, nullable = false)
	public Integer getIdEmployerMaster() {
		return this.idEmployerMaster;
	}

	public void setIdEmployerMaster(Integer idEmployerMaster) {
		this.idEmployerMaster = idEmployerMaster;
	}

	@Column(name = "EMPLOYER_NAME", length = 100)
	public String getEmployerName() {
		return this.employerName;
	}

	public void setEmployerName(String employerName) {
		this.employerName = employerName;
	}

	@Column(name = "EMPLOYER_ADDR1", length = 100)
	public String getEmployerAddr1() {
		return this.employerAddr1;
	}

	public void setEmployerAddr1(String employerAddr1) {
		this.employerAddr1 = employerAddr1;
	}

	@Column(name = "EMPLOYER_ADDR2", length = 100)
	public String getEmployerAddr2() {
		return this.employerAddr2;
	}

	public void setEmployerAddr2(String employerAddr2) {
		this.employerAddr2 = employerAddr2;
	}

	@Column(name = "EMPLOYER_CITY", length = 50)
	public String getEmployerCity() {
		return this.employerCity;
	}

	public void setEmployerCity(String employerCity) {
		this.employerCity = employerCity;
	}

	@Column(name = "EMPLOYER_STATE", length = 50)
	public String getEmployerState() {
		return this.employerState;
	}

	public void setEmployerState(String employerState) {
		this.employerState = employerState;
	}

	@Column(name = "EMPLOYER_PINCODE", length = 10)
	public String getEmployerPincode() {
		return this.employerPincode;
	}

	public void setEmployerPincode(String employerPincode) {
		this.employerPincode = employerPincode;
	}

	@Column(name = "EMPLOYER_COUNTRY", length = 45)
	public String getEmployerCountry() {
		return this.employerCountry;
	}

	public void setEmployerCountry(String employerCountry) {
		this.employerCountry = employerCountry;
	}

	@Column(name = "EMPLOYER_TYPE", length = 45)
	public String getEmployerType() {
		return this.employerType;
	}

	public void setEmployerType(String employerType) {
		this.employerType = employerType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employerMaster")
	public Set getJobPostings() {
		return this.jobPostings;
	}

	public void setJobPostings(Set jobPostings) {
		this.jobPostings = jobPostings;
	}

}
