package in.safety.domain;
// Generated Jul 29, 2017 6:39:12 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobPosting generated by hbm2java
 */
@Entity
@Table(name = "JOB_POSTING", catalog = "SafetyDB")
public class JobPosting implements java.io.Serializable {

	private Integer idJobPosting;
	private EmployerMaster employerMaster;
	private String jobTitle;
	private String jobKeywords;
	private String requiredQualification;
	private String jobDescription;
	private String requiredExperienceDetails;
	private Integer requiredExperience;
	private String gender;
	private Character jobPostingValidity;
	private Date createdDate;
	private Date lastModifiedDate;
	private String featuredJob;
	private Date jobValidTill;
	private String jobLocationCity;
	private String jobLocationAddress;
	private String jobSalaryRange;
	private Set jobPostingJseekers = new HashSet(0);

	public JobPosting() {
	}

	public JobPosting(EmployerMaster employerMaster, String jobTitle, String jobKeywords, String requiredQualification,
			String jobDescription, String requiredExperienceDetails, Integer requiredExperience, String gender,
			Character jobPostingValidity, Date createdDate, Date lastModifiedDate, String featuredJob,
			Date jobValidTill, String jobLocationCity, String jobLocationAddress, String jobSalaryRange,
			Set jobPostingJseekers) {
		this.employerMaster = employerMaster;
		this.jobTitle = jobTitle;
		this.jobKeywords = jobKeywords;
		this.requiredQualification = requiredQualification;
		this.jobDescription = jobDescription;
		this.requiredExperienceDetails = requiredExperienceDetails;
		this.requiredExperience = requiredExperience;
		this.gender = gender;
		this.jobPostingValidity = jobPostingValidity;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.featuredJob = featuredJob;
		this.jobValidTill = jobValidTill;
		this.jobLocationCity = jobLocationCity;
		this.jobLocationAddress = jobLocationAddress;
		this.jobSalaryRange = jobSalaryRange;
		this.jobPostingJseekers = jobPostingJseekers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_JOB_POSTING", unique = true, nullable = false)
	public Integer getIdJobPosting() {
		return this.idJobPosting;
	}

	public void setIdJobPosting(Integer idJobPosting) {
		this.idJobPosting = idJobPosting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_POSTED_BY")
	public EmployerMaster getEmployerMaster() {
		return this.employerMaster;
	}

	public void setEmployerMaster(EmployerMaster employerMaster) {
		this.employerMaster = employerMaster;
	}

	@Column(name = "JOB_TITLE", length = 100)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "JOB_KEYWORDS", length = 200)
	public String getJobKeywords() {
		return this.jobKeywords;
	}

	public void setJobKeywords(String jobKeywords) {
		this.jobKeywords = jobKeywords;
	}

	@Column(name = "REQUIRED_QUALIFICATION", length = 100)
	public String getRequiredQualification() {
		return this.requiredQualification;
	}

	public void setRequiredQualification(String requiredQualification) {
		this.requiredQualification = requiredQualification;
	}

	@Column(name = "JOB_DESCRIPTION", length = 500)
	public String getJobDescription() {
		return this.jobDescription;
	}

	public void setJobDescription(String jobDescription) {
		this.jobDescription = jobDescription;
	}

	@Column(name = "REQUIRED_EXPERIENCE_DETAILS", length = 500)
	public String getRequiredExperienceDetails() {
		return this.requiredExperienceDetails;
	}

	public void setRequiredExperienceDetails(String requiredExperienceDetails) {
		this.requiredExperienceDetails = requiredExperienceDetails;
	}

	@Column(name = "REQUIRED_EXPERIENCE")
	public Integer getRequiredExperience() {
		return this.requiredExperience;
	}

	public void setRequiredExperience(Integer requiredExperience) {
		this.requiredExperience = requiredExperience;
	}

	@Column(name = "GENDER", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "JOB_POSTING_VALIDITY", length = 1)
	public Character getJobPostingValidity() {
		return this.jobPostingValidity;
	}

	public void setJobPostingValidity(Character jobPostingValidity) {
		this.jobPostingValidity = jobPostingValidity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_MODIFIED_DATE", length = 10)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "FEATURED_JOB", length = 20)
	public String getFeaturedJob() {
		return this.featuredJob;
	}

	public void setFeaturedJob(String featuredJob) {
		this.featuredJob = featuredJob;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_VALID_TILL", length = 19)
	public Date getJobValidTill() {
		return this.jobValidTill;
	}

	public void setJobValidTill(Date jobValidTill) {
		this.jobValidTill = jobValidTill;
	}

	@Column(name = "JOB_LOCATION_CITY", length = 100)
	public String getJobLocationCity() {
		return this.jobLocationCity;
	}

	public void setJobLocationCity(String jobLocationCity) {
		this.jobLocationCity = jobLocationCity;
	}

	@Column(name = "JOB_LOCATION_ADDRESS", length = 200)
	public String getJobLocationAddress() {
		return this.jobLocationAddress;
	}

	public void setJobLocationAddress(String jobLocationAddress) {
		this.jobLocationAddress = jobLocationAddress;
	}

	@Column(name = "JOB_SALARY_RANGE", length = 45)
	public String getJobSalaryRange() {
		return this.jobSalaryRange;
	}

	public void setJobSalaryRange(String jobSalaryRange) {
		this.jobSalaryRange = jobSalaryRange;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobPosting")
	public Set getJobPostingJseekers() {
		return this.jobPostingJseekers;
	}

	public void setJobPostingJseekers(Set jobPostingJseekers) {
		this.jobPostingJseekers = jobPostingJseekers;
	}

}
