package in.safety.domain;
// Generated Jul 21, 2017 11:15:05 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobPostingJseeker generated by hbm2java
 */
@Entity
@Table(name = "JOB_POSTING_JSEEKER", catalog = "SafetyDB")
public class JobPostingJseeker implements java.io.Serializable {

	private Integer idJobPostingJseeker;
	private JobPosting jobPosting;
	private JseekerMaster jseekerMaster;

	public JobPostingJseeker() {
	}

	public JobPostingJseeker(JobPosting jobPosting, JseekerMaster jseekerMaster) {
		this.jobPosting = jobPosting;
		this.jseekerMaster = jseekerMaster;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_JOB_POSTING_JSEEKER", unique = true, nullable = false)
	public Integer getIdJobPostingJseeker() {
		return this.idJobPostingJseeker;
	}

	public void setIdJobPostingJseeker(Integer idJobPostingJseeker) {
		this.idJobPostingJseeker = idJobPostingJseeker;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JOB_POSTING")
	public JobPosting getJobPosting() {
		return this.jobPosting;
	}

	public void setJobPosting(JobPosting jobPosting) {
		this.jobPosting = jobPosting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JSEEKER_MASTER")
	public JseekerMaster getJseekerMaster() {
		return this.jseekerMaster;
	}

	public void setJseekerMaster(JseekerMaster jseekerMaster) {
		this.jseekerMaster = jseekerMaster;
	}

}
