package in.safety.domain;
// Generated Jul 21, 2017 11:15:05 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobPosting generated by hbm2java
 */
@Entity
@Table(name = "JOB_POSTING", catalog = "SafetyDB")
public class JobPosting implements java.io.Serializable {

	private Integer idJobPosting;
	private EmployerMaster employerMaster;
	private String jobTitle;
	private String requiredQualification;
	private String jobDescription;
	private Character jobPostingValidity;
	private Date createdDate;
	private Date lastModifiedDate;
	private String featuredJob;
	private Date jobValidTill;
	private String jobLocationCity;
	private Set jobPostingJseekers = new HashSet(0);

	public JobPosting() {
	}

	public JobPosting(EmployerMaster employerMaster, String jobTitle, String requiredQualification,
			String jobDescription, Character jobPostingValidity, Date createdDate, Date lastModifiedDate,
			String featuredJob, Date jobValidTill, String jobLocationCity, Set jobPostingJseekers) {
		this.employerMaster = employerMaster;
		this.jobTitle = jobTitle;
		this.requiredQualification = requiredQualification;
		this.jobDescription = jobDescription;
		this.jobPostingValidity = jobPostingValidity;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
		this.featuredJob = featuredJob;
		this.jobValidTill = jobValidTill;
		this.jobLocationCity = jobLocationCity;
		this.jobPostingJseekers = jobPostingJseekers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_JOB_POSTING", unique = true, nullable = false)
	public Integer getIdJobPosting() {
		return this.idJobPosting;
	}

	public void setIdJobPosting(Integer idJobPosting) {
		this.idJobPosting = idJobPosting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JOB_POSTED_BY")
	public EmployerMaster getEmployerMaster() {
		return this.employerMaster;
	}

	public void setEmployerMaster(EmployerMaster employerMaster) {
		this.employerMaster = employerMaster;
	}

	@Column(name = "JOB_TITLE", length = 100)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "REQUIRED_QUALIFICATION", length = 100)
	public String getRequiredQualification() {
		return this.requiredQualification;
	}

	public void setRequiredQualification(String requiredQualification) {
		this.requiredQualification = requiredQualification;
	}

	@Column(name = "JOB_DESCRIPTION", length = 500)
	public String getJobDescription() {
		return this.jobDescription;
	}

	public void setJobDescription(String jobDescription) {
		this.jobDescription = jobDescription;
	}

	@Column(name = "JOB_POSTING_VALIDITY", length = 1)
	public Character getJobPostingValidity() {
		return this.jobPostingValidity;
	}

	public void setJobPostingValidity(Character jobPostingValidity) {
		this.jobPostingValidity = jobPostingValidity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_MODIFIED_DATE", length = 10)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "FEATURED_JOB", length = 20)
	public String getFeaturedJob() {
		return this.featuredJob;
	}

	public void setFeaturedJob(String featuredJob) {
		this.featuredJob = featuredJob;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "JOB_VALID_TILL", length = 19)
	public Date getJobValidTill() {
		return this.jobValidTill;
	}

	public void setJobValidTill(Date jobValidTill) {
		this.jobValidTill = jobValidTill;
	}

	@Column(name = "JOB_LOCATION_CITY", length = 100)
	public String getJobLocationCity() {
		return this.jobLocationCity;
	}

	public void setJobLocationCity(String jobLocationCity) {
		this.jobLocationCity = jobLocationCity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobPosting")
	public Set getJobPostingJseekers() {
		return this.jobPostingJseekers;
	}

	public void setJobPostingJseekers(Set jobPostingJseekers) {
		this.jobPostingJseekers = jobPostingJseekers;
	}

}
