package in.safety.domain;
// Generated Jul 21, 2017 11:15:05 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JseekerEmploymentDetails generated by hbm2java
 */
@Entity
@Table(name = "JSEEKER_EMPLOYMENT_DETAILS", catalog = "SafetyDB")
public class JseekerEmploymentDetails implements java.io.Serializable {

	private Integer idJseekerEmploymentDetails;
	private JseekerMaster jseekerMaster;
	private String companyName;
	private String designation;
	private Date fromDate;
	private Date toDate;
	private String keyAccomplishments;
	private Date createdDate;
	private Date lastModifiedDate;

	public JseekerEmploymentDetails() {
	}

	public JseekerEmploymentDetails(JseekerMaster jseekerMaster) {
		this.jseekerMaster = jseekerMaster;
	}

	public JseekerEmploymentDetails(JseekerMaster jseekerMaster, String companyName, String designation, Date fromDate,
			Date toDate, String keyAccomplishments, Date createdDate, Date lastModifiedDate) {
		this.jseekerMaster = jseekerMaster;
		this.companyName = companyName;
		this.designation = designation;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.keyAccomplishments = keyAccomplishments;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_JSEEKER_EMPLOYMENT_DETAILS", unique = true, nullable = false)
	public Integer getIdJseekerEmploymentDetails() {
		return this.idJseekerEmploymentDetails;
	}

	public void setIdJseekerEmploymentDetails(Integer idJseekerEmploymentDetails) {
		this.idJseekerEmploymentDetails = idJseekerEmploymentDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JSEEKER_MASTER", nullable = false)
	public JseekerMaster getJseekerMaster() {
		return this.jseekerMaster;
	}

	public void setJseekerMaster(JseekerMaster jseekerMaster) {
		this.jseekerMaster = jseekerMaster;
	}

	@Column(name = "COMPANY_NAME", length = 100)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "DESIGNATION", length = 45)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FROM_DATE", length = 10)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TO_DATE", length = 10)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "KEY_ACCOMPLISHMENTS", length = 200)
	public String getKeyAccomplishments() {
		return this.keyAccomplishments;
	}

	public void setKeyAccomplishments(String keyAccomplishments) {
		this.keyAccomplishments = keyAccomplishments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_MODIFIED_DATE", length = 10)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
