package in.safety.domain;
// Generated Jul 21, 2017 11:15:05 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SkillExperience generated by hbm2java
 */
@Entity
@Table(name = "SKILL_EXPERIENCE", catalog = "SafetyDB")
public class SkillExperience implements java.io.Serializable {

	private Integer idSkillExperience;
	private JseekerMaster jseekerMaster;
	private String skillName;
	private Integer skillExperience;
	private Date createdDate;
	private Date lastModifiedDate;

	public SkillExperience() {
	}

	public SkillExperience(JseekerMaster jseekerMaster) {
		this.jseekerMaster = jseekerMaster;
	}

	public SkillExperience(JseekerMaster jseekerMaster, String skillName, Integer skillExperience, Date createdDate,
			Date lastModifiedDate) {
		this.jseekerMaster = jseekerMaster;
		this.skillName = skillName;
		this.skillExperience = skillExperience;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_SKILL_EXPERIENCE", unique = true, nullable = false)
	public Integer getIdSkillExperience() {
		return this.idSkillExperience;
	}

	public void setIdSkillExperience(Integer idSkillExperience) {
		this.idSkillExperience = idSkillExperience;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JSEEKER_MASTER", nullable = false)
	public JseekerMaster getJseekerMaster() {
		return this.jseekerMaster;
	}

	public void setJseekerMaster(JseekerMaster jseekerMaster) {
		this.jseekerMaster = jseekerMaster;
	}

	@Column(name = "SKILL_NAME", length = 100)
	public String getSkillName() {
		return this.skillName;
	}

	public void setSkillName(String skillName) {
		this.skillName = skillName;
	}

	@Column(name = "SKILL_EXPERIENCE")
	public Integer getSkillExperience() {
		return this.skillExperience;
	}

	public void setSkillExperience(Integer skillExperience) {
		this.skillExperience = skillExperience;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE", length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_MODIFIED_DATE", length = 10)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
