package in.safety.domain;
// Generated Jul 29, 2017 6:39:12 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Testimonials generated by hbm2java
 */
@Entity
@Table(name = "TESTIMONIALS", catalog = "SafetyDB")
public class Testimonials implements java.io.Serializable {

	private Integer idTestimonials;
	private String testimonialsText;
	private String testimonialsFrom;
	private byte[] testimonialsSnap;

	public Testimonials() {
	}

	public Testimonials(String testimonialsText) {
		this.testimonialsText = testimonialsText;
	}

	public Testimonials(String testimonialsText, String testimonialsFrom, byte[] testimonialsSnap) {
		this.testimonialsText = testimonialsText;
		this.testimonialsFrom = testimonialsFrom;
		this.testimonialsSnap = testimonialsSnap;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_TESTIMONIALS", unique = true, nullable = false)
	public Integer getIdTestimonials() {
		return this.idTestimonials;
	}

	public void setIdTestimonials(Integer idTestimonials) {
		this.idTestimonials = idTestimonials;
	}

	@Column(name = "TESTIMONIALS_TEXT", nullable = false, length = 500)
	public String getTestimonialsText() {
		return this.testimonialsText;
	}

	public void setTestimonialsText(String testimonialsText) {
		this.testimonialsText = testimonialsText;
	}

	@Column(name = "TESTIMONIALS_FROM", length = 100)
	public String getTestimonialsFrom() {
		return this.testimonialsFrom;
	}

	public void setTestimonialsFrom(String testimonialsFrom) {
		this.testimonialsFrom = testimonialsFrom;
	}

	@Column(name = "TESTIMONIALS_SNAP")
	public byte[] getTestimonialsSnap() {
		return this.testimonialsSnap;
	}

	public void setTestimonialsSnap(byte[] testimonialsSnap) {
		this.testimonialsSnap = testimonialsSnap;
	}

}
